markdown: redcarpet
pygments: true
permalink: /:categories/:year/:month/:day/:title
paginate: 4
paginate_path: "index:num/"

author:
  name: Marin Vila
  github: rinmalavi
  twitter: vila_marin

comments :
    provider : disqus
    disqus :
        short_name : marinvila


#  analytics :
#    provider : google
#
#    google :
#        tracking_id : 'UA-123-12'
