permalink: /:categories/:title
author:
  name: Marin Vila
  github: rinmalavi
  twitter: vila_marin

comments :
    provider : disqus
    disqus :
        short_name : marinvila


#  analytics :
#    provider : google
#
#    google :
#        tracking_id : 'UA-66960621-1'
